version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "dev-team"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "eslint*"
        versions: ["6.x", "7.x"]
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    registries: "*"

registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_PASSWORD }}

enable-beta-ecosystems: true
enable-security-updates: true
security-updates:
  labels: ["security"]
  assignees: ["security-team"]
rebase-strategy: "auto"
max-dependency-updates: 10
